[project]
name = "energy-data-service"
version = "0.1.0"
description = "Professional data service for energy trading signals"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.4",
    "apscheduler>=3.11.0",
    "asyncpg>=0.30.0",
    "dependency-injector>=4.48.1",
    "entsoe-client",
    "fastapi>=0.116.1",
    "greenlet>=3.2.3",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "python-dateutil>=2.8.2",
    "sqlalchemy>=2.0.41",
    "structlog>=25.4.0",
    "types-python-dateutil>=2.9.0.20250708",
    "uvicorn>=0.35.0",
]

[tool.uv.sources]
entsoe-client = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-xdist>=3.6.0",
    "testcontainers>=4.12.0",
]

[tool.setuptools]
packages = ["app"]
package-dir = {"" = "."}

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-n auto --dist worksteal"
asyncio_mode = "auto"
