# Jekyll / Just the Docs configuration
title: Energy Trading Project
description: Production-quality energy market data collection, processing, and storage for trading signals and analytics.
url: "https://aldairpetronilia.github.io"
baseurl: "/trading-project"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: "energy"
# Enable/disable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true
  button: true

# Navigation / UI
logo: "/trading-project/docs/assets/logo.svg"
favicon_ico: "/trading-project/docs/assets/favicon.svg"
aux_links:
  "GitHub":
    - "//github.com/AldairPetronilia/trading-project"
aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"

# Pages shown in top header (optional; sidebar still shows full nav)
header_pages:
  - index.md
  - getting-started.md
  - architecture.md
  - api.md
  - deployment.md

# Edit this page links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/AldairPetronilia/trading-project"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Footer
footer_content: >-
  Copyright &copy; {{"{{"}} site.time | date: "%Y" {{"}}"}} Energy Trading Project —
  <a href="https://github.com/AldairPetronilia/trading-project/blob/main/LICENSE">MIT License</a>

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %H:%M"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Markdown / syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Collections (optional future expansion)
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/

repository: AldairPetronilia/trading-project
author: Aldair Petronilia
